    BOND_CODE      VARCHAR(50) NOT NULL
    ,BONE_NAME      VARCHAR(50) NOT NULL
    ,MATURITY       VARCHAR(10) NOT NULL
    ,COUPON         DECIMAL(18,12) NOT NULL  
    ,BOOK_VALUE     DECIMAL(32,12) NOT NULL
    ,FAIR_VALUE     DECIMAL(32,12) 
    ,AMOUNT         DECIMAL(10,0)  NOT NULL
    ,DELETE_FLAG    BOOL NOT NULL
    ,primary key(BOND_CODE)
)